import 'package:ttt/core/localization/app_strings.dart';

//Map that's responsible for Translating language from English to Arabic
Map<String, String> arabicLanguage = {
  //app Strings
  AppStrings.onlineFreeClassifieds: "إعلانات مبوبة مجانية على الإنترنت",
  AppStrings.from: "بواسطة",
  AppStrings.smartOnlineSolutions: "سمارت أونلاين سوليوشن",
  AppStrings.login: "تسجيل الدخول",
  AppStrings.welcome: "مرحبا بك ",
  AppStrings.loginSubtitle: "أهلا بك في آمان قم بتسجيل الدخول الآن",
  AppStrings.typeEmail: "أكتب البريد الإلكتروني",
  AppStrings.password: "كلمة المرور",
  AppStrings.forgotPassword: "هل نسيت كلمة السر؟",
  AppStrings.orLoginWith: "أو تسجيل الدخول بواسطة",
  AppStrings.dontHaveAccount: "ليس لديك حساب ؟",
  AppStrings.signIn: "تسجيل الدخول",
  AppStrings.signUp: "إنشاء حساب",
  AppStrings.fullName: "الاسم الكامل",
  AppStrings.typeName: "أكتب الاسم",
  AppStrings.typePhoneNumber: " أكتب رقم الهاتف",
  AppStrings.phoneNumber: "رقم الهاتف",
  AppStrings.typePassword: "أكتب كلمة المرور",
  AppStrings.confirmAndSend: 'تأكيد وإرسال',
  AppStrings.byCreatingAnAccountYouAgree:
      "من خلال إنشاء حساب، فإنك توافق على اتفاقية المستخدم الخاصة بنا وتقر بقراءة إشعار خصوصية المستخدم الخاص بنا",
  AppStrings.doYouHaveAnAccount: "هل لديك حساب ؟",
  AppStrings.orSignUpWith: "أو إنشاء الحساب بواسطة",
  AppStrings.needHelp: "تحتاج مساعدة",
  AppStrings.continueAsGuest: "الاستمرار كزائر",
  AppStrings.country: 'الدولة',
  AppStrings.typeAd: "اكتب إعلان",
  AppStrings.shareApp: 'شارك التطبيق',
  AppStrings.help: 'يساعد',
  AppStrings.contactUs: 'اتصل بنا',
  AppStrings.aboutUs: 'معلومات عنا',
  AppStrings.readMore: '  اقرأ المزيد',
  AppStrings.numberOfRatings: ' عدد التقييمات',
  AppStrings.notifications: 'الإشعارات',
  AppStrings.messages: 'الرسائل',
  AppStrings.rate: 'تقييم',
  AppStrings.customerReviews: 'آراء العملاء',
  AppStrings.search: 'بحث....',
  AppStrings.copyRights:
      '@ السوق اون لاين، جميع الحقوق محفوظة 2023 version1.01(build:1011010)',
  AppStrings.followUs: 'اتبعنا',
  AppStrings.readLess: 'اقرأ أقل',
  AppStrings.privacyPolicy: 'سياسة الخصوصية',
  AppStrings.termsAConditions: 'الأحكام والشروط',
  AppStrings.termsAndConditions: 'الأحكام والشروط',
  AppStrings.changeTheme: 'غير الخلفية',
  AppStrings.dark: 'مظلم',
  AppStrings.light: 'ضوء',
  AppStrings.systemMode: 'وضع النظام',
  AppStrings.darkMode: 'الوضع المظلم',
  AppStrings.changeLocation: "تغيير الدولة",
  AppStrings.language: "اللغة",
  AppStrings.language_subtitle: "أختر اللغة التي تريد المتابعة في التطبيق بها",
  AppStrings.changeLanguage: 'تغيير اللغة',
  AppStrings.fromSmartOnline: 'من\nالحلول الذكية عبر الإنترنت',
  //core strings

  AppStrings.email: 'الحساب الالكتروني',
  AppStrings.resetPassword: "إعادة تعيين كلمة المرور",
  AppStrings.logInFailed: 'فشل تسجيل الدخول',
  AppStrings.connectionError: "هناك مشكلة بالاتصال",
  AppStrings.newPassword: 'كلمة المرور الجديدة',
  AppStrings.confirmPassword: 'تأكيد كلمة المرور',
  AppStrings.pleaseConfirmPassword: 'يرجى تأكيد كلمة المرور',
  AppStrings.pleaseNotValidEmpty: 'كلمة المرور غير صالحة فارغة',
  AppStrings.andAcknowledge: ' والاعتراف بقراءة لدينا ',
  AppStrings.userPrivacyNotice: ' إشعار خصوصية المستخدم',
  AppStrings.typeInYourCode: "اكتب الرمز الخاص بك",
  AppStrings.weSentASecurityCode: " لقد أرسلنا رمز الحماية إلى",
  AppStrings.yourAccount: ' الحساب الخاص بك ',
  AppStrings.resend: 'إعادة إرسال',
  AppStrings.code: "شفرة",
  AppStrings.enterCode: 'ادخل الرمز',
  AppStrings.continu: 'استمر',
  AppStrings.tryAnotherWay: "جرب طريقة أخرى",
  AppStrings.enter6DigitCode: "أدخل الرمز المكون من 6 أرقام",
  AppStrings.youMayNeedToCheck:
      "قد تحتاج إلى التحقق من مجلد الرسائل غير المرغوب فيها أو البريد العشوائي",

  AppStrings.onboarding_title_1: 'مرحبًا بك في آمان',
  AppStrings.onboarding_subtitle_1:
      '( تطبيقنا يقدم مجموعة واسعة من الخدمات من صيانة عامة للمبانى السكنية و تصليح الاجهزة المنزلية و التنظيف و أكثر من ذلك من الخدمات المتنوعة ) اكتشف كيف يمككنا مساعتدك',
  AppStrings.onboarding_title_2: "تواصل مباشر مع الفنيين والشركات",
  AppStrings.onboarding_subtitle_2:
      "احصل على دعم فوري واستجابة سريعة من خلال التواصل مباشرة مع الفنيين المهنيين أو الشركات عن طريق الدردشة المباشرة, الآن لن تكون تحت رحمة, إستغلالة الصنايعي او المقاول",
  AppStrings.onboarding_title_3: "تعرف على كيفية التفاعل مع الأسعار",
  AppStrings.onboarding_subtitle_3:
      "اطلع على تفاصيل الخدمات والأسعار المعروضة والتكاليف المتعلقة بها. بعد ذلك، قم باختيار السعر الذي يناسبك ويتوافق مع احتياجاتك وميزانيتك , وأنسي آي حد يستغلك",
  AppStrings.skip: "تخطى",
  AppStrings.previous: "السابق",
  AppStrings.accountType: "أختر نوع الحساب",
  AppStrings.accountType_subtitle: "قم بتحديد نوع الحساب للاستمرار في ",
  AppStrings.enterTheCodeThatWasSentTo: "ادخل الكود الذي تم ارسالة الى",
  AppStrings.passwordRecovery: " لاسترجاع كلمة المرور الخاصة بك",
  AppStrings.send: "ارسال",
  AppStrings.youHaveNtReceivedYourCodeYet: 'لم تستلم الرمز بعد؟',
  AppStrings.codeSent: 'تم إرسال الرمز',
  AppStrings.enterStrongPassword:
      '       ادخل كلمة مرور قوية تحتوي على الاقل 8 رموز مكونة من حروف و ارقام ',
  AppStrings.passwordMustBeEntered: 'يجب إدخال كلمة المرور',
  AppStrings.passwordMustBeAtEightCharacters:
      'يجب أن تكون كلمة المرور على الأقل ثمانية أحرف',
  AppStrings.passwordMustBeConfirmed: 'يجب تأكيد كلمة المرور',
  AppStrings.passwordDoesNotMatch: 'كلمة المرور غير متطابقة',
  AppStrings.confirm: 'تاكيد',
  AppStrings.addCardImage: 'إضافة صورة البطاقة',
  AppStrings.mandatory: 'إلزامية',
  AppStrings.completeYourData: 'استكمل بياناتك',
  AppStrings.idCardNumber: "رقم بطاقة الهوية,",
  AppStrings.companyOrTechnicianName: 'اسم الشركة أو الفني',
  AppStrings.serviceProviderType: "نوع مزود الخدمة",
  AppStrings.addBanner: "إضافة بانر لحسابك",
  AppStrings.download: "التحميل",
  AppStrings.next: "التالي",
  AppStrings.dropHereToAttachOr: 'أسقط هنا للإرفاق أو ',
  AppStrings.maximumSize: ' أقصي حجم',
  AppStrings.addPhoto: "إضافة صورة لحسابك",
  AppStrings.aboutYou: ' نبذة عنك',
  AppStrings.city: 'المدينة',
  AppStrings.conservative: " محافظة",
  AppStrings.technical: 'فني',
  AppStrings.state: 'الدولة',
  AppStrings.company: 'شركة',
  AppStrings.review: 'مراجعة',
  AppStrings.showMore: 'عرض المزيد',
  AppStrings.selectTheServicesYouProvide: 'اختر الخدمات التي تقدمها',
  AppStrings.Enterthedatatoactivationofyouraccount:
      'أدخل البيانات لأستكمال تفعيل حسابك',
  AppStrings.supplierData: "بيانات المزود",
  AppStrings.activationPapers: "أوراق التفعيل",
  AppStrings.documentExpiryDate: "تاريخ انتهاء المستند",
  AppStrings.license: "الرخصة أو السجل التجاري",
  AppStrings.licenseExpiryDate: "تاريخ انتهاء الرخصة",
  AppStrings.user: "مستخدم",
  AppStrings.companyOrTechnician: "شركة أو فني",
  AppStrings.requiredField: "هذه الخانة مطلوبه",
  AppStrings.infoSend: "تم ارسال البيانات بنجاح",
  AppStrings.all: "الكل",
  AppStrings.active: "نشط",
  AppStrings.expired: "منتهي",
  AppStrings.myOrders: "طلباتي",
  AppStrings.youReceived: "لقد تلقيت",
  AppStrings.offer: "عرض",
  AppStrings.showDetails: 'عرض التفاصيل',
  AppStrings.numberOfUnit: "عدد الوحدات",
  AppStrings.unitType: 'نوع الوحدة',
  AppStrings.orderNumber: "رقم الطلب",
  AppStrings.viewOffer: "مشاهدة العروض",
  AppStrings.duration: 'الوقت المفضل للتنفيذ',
  AppStrings.orderDetails: 'تفاصيل الطلب',
  AppStrings.cancelOrder: "الغاء الطلب",
  AppStrings.problem: "مشكلة",
  AppStrings.cost: "التكلفة",
  AppStrings.chat: "درشة",
  AppStrings.report: "تبليغ عن مشكلة",
  AppStrings.reOrder: "إعادة طلب",
  AppStrings.allOffer: "جميع العروض",
  AppStrings.favorite: "المفضلة",
  AppStrings.expectedDuraction: "الوقت المتوقع",
  AppStrings.visitCode: "تكلفة الزيارة",
  AppStrings.offerPrice: "سعر العرض",
  AppStrings.warranty: "الضمان",
  AppStrings.confirmOrder: "تأكيد العرض",
  AppStrings.deniedOrder: "رفض الطلب",
  AppStrings.offerDetails: "تفاصيل العرض",
  AppStrings.previousWork: "الأعمال السابقة",
  AppStrings.askProvider: "اسأل المزود",
  AppStrings.order: "طلب",
  AppStrings.time: "المدة",
  AppStrings.place: "المكان",
  AppStrings.orderDescription: "وصف الطلب",
  AppStrings.descripe: 'اوصف مشكلتك وحاجتك بوضوح',
  AppStrings.choosetheservice: 'اختار نوع الخدمة المطلوب تنفيذها',
  AppStrings.chooseTime: 'اختار الوقت المفضل للتنفيذ',
  AppStrings.selectUnit: 'اختر نوع الوحدة',
  AppStrings.selectLocation: ' اختيار الموقع',
  AppStrings.saveUpdate: 'حفظ التعديلات',
  AppStrings.serviceType: 'نوع الخدمة',
  AppStrings.delete: 'حذف',
  AppStrings.enterThePasswordToDelete: 'أدخل كلمة السر لحذف الحساب',
  AppStrings.currentLocation: " الموقع الحالي",
  AppStrings.startNow: "أبدا الان",
  AppStrings.previousLocation: "المواقع السابق",
  AppStrings.addRequest: 'اضافة طلب جديد',
  AppStrings.confirmAccount: 'تأكيد الحساب',
  AppStrings.askQuestions:
      'سنسألك بعض الأسئلة لجمع التفاصيل حول طلبك وإرسالها للشركات والفنيين',
  AppStrings.day: "اليوم",
  AppStrings.optional: "اختياري",
  AppStrings.offerCode: 'ادخل كود العرض',
  AppStrings.entertheoffercode: 'ادخل كود العرض إذا كان لديك',
  AppStrings.addphotoandimage: 'إضافة صور و فيديو',
  AppStrings.addmorepicture:
      "اضف أكثر من صوره للمشكلة حتي يسهل تحديد وفهم المشكلة",
  AppStrings.registerServiceProvider: 'تسجيل مزود خدمة',
  AppStrings.changePassword: 'تغير كلمة المرور',
  AppStrings.safetyValues: 'قيم آمان',
  AppStrings.aboutServices: 'حول خدمات',
  AppStrings.cancel: 'إلغاء',
  AppStrings.myAccount: 'حسابي',
  AppStrings.completedOrders: 'الطلبات المنتهيه',
  AppStrings.serviceProviderInformation: 'معلومات مزود الخدمة',
  AppStrings.phoneNumberMustBeEntered: 'رقم الهاتف يجب إدخاله',
  AppStrings.areYouSureToLogOut: 'هل أنت متاكد من تسجيل الخروج',
  AppStrings.areYouSureWantToDeleteAccount: 'هل أنت متاكد من حذف الحساب',
  AppStrings.deleteAccount: 'حذف حساب',
  AppStrings.yes: 'نعم',
  AppStrings.logout: 'تسجيل الخروج',
  AppStrings.no: 'لا',
  AppStrings.emailMustBeEntered: "يجب إدخال البريد الإلكتروني",
  AppStrings.editYourInformation: 'تعديل بياناتك',
  AppStrings.enterName: 'ادخل الاسم',
  AppStrings.nameMustBeEntered: 'يجب إدخال الاسم',
  AppStrings.currentPassword: 'كلمة المرور الحاليه',
  AppStrings.chooseLanguage: 'اختر لغة التطبيق',
  AppStrings.problemDescription: "وصف المشكلة",
  AppStrings.attachFile: "ارفق الملفات",
  AppStrings.attachFileSubtitle:
      "اضف أكثر من صوره للمشكلة حتي يسهل تحديد وفهم المشكلة",
  AppStrings.reorderTitle: "إعادة طلب الخدمة",
  AppStrings.reorderSubtitle:
      "برجاء ادخال المدة التي تحتاجها لاعادة طلب الخدمة",
  AppStrings.ok: "حسنا",
  AppStrings.orderConfirmed: "تم تاكيد الطلب",
  AppStrings.someThingWentWrong: "حدث خطأ",
  AppStrings.paymentTitle: "أختر طريقة الدفع المناسبة",
  AppStrings.vodafoneCash: "فودافون كاش",
  AppStrings.instaPay: "انستا باي",
  AppStrings.coupon: "كود مجاني",
  AppStrings.sendRequestCost:
      "ارسل تكلفة الطلب المذكورة الي الرقم بالاسفل ثم ارفع صورة تأكيدية عملية التحويل",
  AppStrings.transferNumber: "رقم التحويل",
  AppStrings.clickUploadImage: "اضغط هنا لرفع صورة تأكيدية التحويل",
  AppStrings.enterTheNumber: "ادخل الرقم الذي قمت بالتحويل منه",
  AppStrings.transferAccount: "حساب التحويل",
  AppStrings.transferAccountSendFrom: "ادخل الحساب الذي قمت بالتحويل منه",
  AppStrings.enterTheCode: "ادخل الكود المجاني للاستمرار",
  AppStrings.allOrders: "جميع الطلبات",
  AppStrings.acceptOffers: "العروض المقبولة",
  AppStrings.makeOffer: "تقديم عرض",
  AppStrings.area: "المنطقة",
  AppStrings.location: "الموقع",
  AppStrings.addANameForThePickedLocation: "أضف اسم لهذا العنوان",
  AppStrings.add: "اضافة",
  AppStrings.pleaseEnableLocationService: "يرجى تفعيل خدمة الموقع",
  AppStrings.attachedFiles: "الملفات المرفقة",
  AppStrings.myOfferDetails: "تفاصيل عرضي",
  AppStrings.doWantToEnd: "هل تريد إنهاء الخدمة",
  AppStrings.finish: "انهاء",
  AppStrings.resendCode: "اعد الإرسال بعد",
  AppStrings.youGot: "يوجد لديك ",
  AppStrings.request: "  طلب",
  AppStrings.witth: "عليه",
  AppStrings.viewAllOffer: "مشاهدة كافة العروض",
  AppStrings.providedServices: "الخدمات المتاحة",
  AppStrings.noDataFound: "لا يوجد بيانات",
  AppStrings.itSeamsLikeYouHaveNotPickedALocation: "لا يوجد موقع محدد",
  AppStrings.letsDoItAgain: "يمكنك المحاولة مرة أخرى",
  AppStrings.today: "اليوم",
  AppStrings.tomorrow: "غدا",
  AppStrings.nextWeek: "الأسبوع التالي",
  AppStrings.duringWeek: "خلال الاسبوع",
  AppStrings.completed: "منتهي",
  AppStrings.cancelled: "تم الإلغاء",
  AppStrings.months: "شهور",
  AppStrings.immediately: "فورا",
  AppStrings.alreadyBooked: "محجوز من قبل",
};
