//Map that's responsible for English Language
import 'package:ttt/core/localization/app_strings.dart';

Map<String, String> englishLanguage = {
  AppStrings.onlineFreeClassifieds: "ONLINE FREE CLASSIFIEDS",
  AppStrings.from: "From",
  AppStrings.smartOnlineSolutions: "Smart Online Solutiions",
  AppStrings.login: "Login",
  AppStrings.welcome: AppStrings.welcome,
  AppStrings.loginSubtitle: AppStrings.loginSubtitle,
  AppStrings.typeEmail: "Type email",
  AppStrings.password: "Password\t",
  AppStrings.forgotPassword: "Forgot Password?",
  AppStrings.orLoginWith: "Or login with",
  AppStrings.dontHaveAccount: "Don’t have an account ?",
  AppStrings.signUp: "Sing up",
  AppStrings.fullName: "Full Name",
  AppStrings.typeName: "Type name ",
  AppStrings.confirmAndSend: AppStrings.confirmAndSend,
  AppStrings.typePhoneNumber: " Type Phone number",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.typePassword: "Type password",
  AppStrings.byCreatingAnAccountYouAgree:
      "by creating an account, you agree to our User Agreement and acknowledge reading our User Privacy Notice",
  AppStrings.doYouHaveAnAccount: "Do you have an account ?",
  AppStrings.orSignUpWith: "Or sign up with",
  AppStrings.needHelp: "Need Help ",
  AppStrings.resetPassword: AppStrings.resetPassword,
  AppStrings.continueAsGuest: AppStrings.continueAsGuest,
  AppStrings.email: AppStrings.email,
  AppStrings.connectionError: AppStrings.connectionError,
  AppStrings.logInFailed: AppStrings.logInFailed,
  AppStrings.newPassword: AppStrings.newPassword,
  AppStrings.confirmPassword: AppStrings.confirmPassword,
  AppStrings.pleaseConfirmPassword: AppStrings.pleaseConfirmPassword,
  AppStrings.pleaseNotValidEmpty: AppStrings.pleaseNotValidEmpty,
  AppStrings.andAcknowledge: AppStrings.andAcknowledge,
  AppStrings.userPrivacyNotice: AppStrings.userPrivacyNotice,
  AppStrings.typeInYourCode: AppStrings.typeInYourCode,
  AppStrings.yourAccount: AppStrings.yourAccount,
  AppStrings.youMayNeedToCheck: AppStrings.youMayNeedToCheck,
  AppStrings.weSentASecurityCode: AppStrings.weSentASecurityCode,
  AppStrings.resend: AppStrings.resend,
  AppStrings.code: AppStrings.code,
  AppStrings.continu: AppStrings.continu,
  AppStrings.country: AppStrings.country,
  AppStrings.language: AppStrings.language,
  AppStrings.language_subtitle: AppStrings.language_subtitle,
  AppStrings.typeAd: AppStrings.typeAd,
  AppStrings.darkMode: AppStrings.darkMode,
  AppStrings.dark: AppStrings.dark,
  AppStrings.light: AppStrings.light,
  AppStrings.systemMode: AppStrings.systemMode,
  AppStrings.changeTheme: AppStrings.changeTheme,
  AppStrings.shareApp: AppStrings.shareApp,
  AppStrings.help: AppStrings.help,
  AppStrings.contactUs: AppStrings.contactUs,
  AppStrings.numberOfRatings: AppStrings.numberOfRatings,
  AppStrings.aboutUs: AppStrings.aboutUs,
  AppStrings.privacyPolicy: AppStrings.privacyPolicy,
  AppStrings.termsAConditions: AppStrings.termsAConditions,
  AppStrings.termsAndConditions: AppStrings.termsAndConditions,
  AppStrings.changeLocation: AppStrings.changeLocation,
  AppStrings.notifications: AppStrings.notifications,
  AppStrings.messages: AppStrings.messages,
  AppStrings.readMore: AppStrings.readMore,
  AppStrings.showMore: AppStrings.showMore,
  AppStrings.review: AppStrings.review,
  AppStrings.rate: AppStrings.rate,
  AppStrings.customerReviews: AppStrings.customerReviews,
  AppStrings.changeLanguage: AppStrings.changeLanguage,
  AppStrings.fromSmartOnline: AppStrings.fromSmartOnline,
  AppStrings.tryAnotherWay: AppStrings.tryAnotherWay,
  AppStrings.readLess: AppStrings.readLess,
  AppStrings.enterCode: AppStrings.enterCode,
  AppStrings.followUs: AppStrings.followUs,
  AppStrings.search: AppStrings.search,
  AppStrings.copyRights: AppStrings.copyRights,
  AppStrings.enter6DigitCode: AppStrings.enter6DigitCode,
  AppStrings.onboarding_title_1: AppStrings.onboarding_title_1,
  AppStrings.onboarding_subtitle_1: AppStrings.onboarding_subtitle_1,
  AppStrings.onboarding_title_2: AppStrings.onboarding_title_2,
  AppStrings.onboarding_subtitle_2: AppStrings.onboarding_subtitle_2,
  AppStrings.onboarding_title_3: AppStrings.onboarding_title_3,
  AppStrings.onboarding_subtitle_3: AppStrings.onboarding_subtitle_3,
  AppStrings.skip: AppStrings.skip,
  AppStrings.previous: AppStrings.previous,
  AppStrings.accountType: AppStrings.accountType,
  AppStrings.accountType_subtitle: AppStrings.accountType_subtitle,
  AppStrings.enterTheCodeThatWasSentTo: AppStrings.enterTheCodeThatWasSentTo,
  AppStrings.passwordRecovery: AppStrings.passwordRecovery,
  AppStrings.send: AppStrings.send,
  AppStrings.youHaveNtReceivedYourCodeYet:
      AppStrings.youHaveNtReceivedYourCodeYet,
  AppStrings.codeSent: AppStrings.codeSent,
  AppStrings.enterStrongPassword: AppStrings.enterStrongPassword,
  AppStrings.passwordMustBeEntered: AppStrings.passwordMustBeEntered,
  AppStrings.passwordMustBeAtEightCharacters:
      AppStrings.passwordMustBeAtEightCharacters,
  AppStrings.passwordMustBeConfirmed: AppStrings.passwordMustBeConfirmed,
  AppStrings.addCardImage: AppStrings.addCardImage,
  AppStrings.mandatory: AppStrings.mandatory,
  AppStrings.passwordDoesNotMatch: AppStrings.passwordDoesNotMatch,
  AppStrings.confirm: AppStrings.confirm,
  AppStrings.idCardNumber: AppStrings.idCardNumber,
  AppStrings.completeYourData: AppStrings.completeYourData,
  AppStrings.companyOrTechnicianName: AppStrings.companyOrTechnicianName,
  AppStrings.serviceProviderType: AppStrings.serviceProviderType,
  AppStrings.addBanner: AppStrings.addBanner,
  AppStrings.download: AppStrings.download,
  AppStrings.next: AppStrings.next,
  AppStrings.maximumSize: AppStrings.maximumSize,
  AppStrings.dropHereToAttachOr: AppStrings.dropHereToAttachOr,
  AppStrings.addPhoto: AppStrings.addPhoto,
  AppStrings.aboutYou: AppStrings.aboutYou,
  AppStrings.city: AppStrings.city,
  AppStrings.conservative: AppStrings.conservative,
  AppStrings.state: AppStrings.state,
  AppStrings.company: AppStrings.company,
  AppStrings.technical: AppStrings.technical,
  AppStrings.selectTheServicesYouProvide:
      AppStrings.selectTheServicesYouProvide,
  AppStrings.Enterthedatatoactivationofyouraccount:
      AppStrings.Enterthedatatoactivationofyouraccount,
  AppStrings.supplierData: AppStrings.supplierData,
  AppStrings.activationPapers: AppStrings.activationPapers,
  AppStrings.documentExpiryDate: AppStrings.documentExpiryDate,
  AppStrings.license: AppStrings.license,
  AppStrings.licenseExpiryDate: AppStrings.licenseExpiryDate,
  AppStrings.user: AppStrings.user,
  AppStrings.companyOrTechnician: AppStrings.companyOrTechnician,
  AppStrings.requiredField: AppStrings.requiredField,
  AppStrings.infoSend: AppStrings.infoSend,
  AppStrings.all: AppStrings.all,
  AppStrings.active: AppStrings.active,
  AppStrings.expired: AppStrings.expired,
  AppStrings.myOrders: AppStrings.myOrders,
  AppStrings.youReceived: AppStrings.youReceived,
  AppStrings.offer: AppStrings.offer,
  AppStrings.orderNumber: AppStrings.orderNumber,
  AppStrings.viewOffer: AppStrings.viewOffer,
  AppStrings.cancelOrder: AppStrings.cancelOrder,
  AppStrings.descripe: AppStrings.descripe,
  AppStrings.chooseTime: AppStrings.chooseTime,
  AppStrings.day: AppStrings.day,
  AppStrings.offerCode: AppStrings.offerCode,
  AppStrings.optional: AppStrings.optional,
  AppStrings.entertheoffercode: AppStrings.entertheoffercode,
  AppStrings.addphotoandimage: AppStrings.addphotoandimage,
  AppStrings.addmorepicture: AppStrings.addmorepicture,
  AppStrings.selectLocation: AppStrings.selectLocation,
  AppStrings.confirmOrder: AppStrings.confirmOrder,
  AppStrings.serviceType: AppStrings.serviceType,
  AppStrings.place: AppStrings.place,
  AppStrings.orderDescription: AppStrings.orderDescription,
  AppStrings.currentLocation: AppStrings.currentLocation,
  AppStrings.previousLocation: AppStrings.previousLocation,
  AppStrings.addRequest: AppStrings.addRequest,
  AppStrings.askQuestions: AppStrings.askQuestions,
  AppStrings.startNow: AppStrings.startNow,
  AppStrings.choosetheservice: AppStrings.choosetheservice,
  AppStrings.selectUnit: AppStrings.selectUnit,
  AppStrings.changePassword: AppStrings.changePassword,
  AppStrings.safetyValues: AppStrings.safetyValues,
  AppStrings.aboutServices: AppStrings.aboutServices,
  AppStrings.deleteAccount: AppStrings.deleteAccount,
  AppStrings.yes: AppStrings.yes,
  AppStrings.no: AppStrings.no,
  AppStrings.logout: AppStrings.logout,
  AppStrings.cancel: AppStrings.cancel,
  AppStrings.saveUpdate: AppStrings.saveUpdate,
  AppStrings.myAccount: AppStrings.myAccount,
  AppStrings.confirmAccount: AppStrings.confirmAccount,
  AppStrings.emailMustBeEntered: AppStrings.emailMustBeEntered,
  AppStrings.phoneNumberMustBeEntered: AppStrings.phoneNumberMustBeEntered,
  AppStrings.areYouSureToLogOut: AppStrings.areYouSureToLogOut,
  AppStrings.areYouSureWantToDeleteAccount:
      AppStrings.areYouSureWantToDeleteAccount,
  AppStrings.editYourInformation: AppStrings.editYourInformation,
  AppStrings.enterName: AppStrings.enterName,
  AppStrings.showDetails: AppStrings.showDetails,
  AppStrings.delete: AppStrings.delete,
  AppStrings.enterThePasswordToDelete: AppStrings.enterThePasswordToDelete,
  AppStrings.unitType: AppStrings.unitType,
  AppStrings.numberOfUnit: AppStrings.numberOfUnit,
  AppStrings.duration: AppStrings.duration,
  AppStrings.orderDetails: AppStrings.orderDetails,
  AppStrings.nameMustBeEntered: AppStrings.nameMustBeEntered,
  AppStrings.currentPassword: AppStrings.currentPassword,
  AppStrings.registerServiceProvider: AppStrings.registerServiceProvider,
  AppStrings.chooseLanguage: AppStrings.chooseLanguage,
  AppStrings.completedOrders: AppStrings.completedOrders,
  AppStrings.serviceProviderInformation: AppStrings.serviceProviderInformation,
  AppStrings.problem: AppStrings.problem,
  AppStrings.problemDescription: AppStrings.problemDescription,
  AppStrings.attachFile: AppStrings.attachFile,
  AppStrings.attachFileSubtitle: AppStrings.attachFileSubtitle,
  AppStrings.reorderTitle: AppStrings.reorderTitle,
  AppStrings.reorderSubtitle: AppStrings.reorderSubtitle,
  AppStrings.ok: AppStrings.ok,
  AppStrings.orderConfirmed: AppStrings.orderConfirmed,
  AppStrings.someThingWentWrong: AppStrings.someThingWentWrong,
  AppStrings.paymentTitle: AppStrings.paymentTitle,
  AppStrings.vodafoneCash: AppStrings.vodafoneCash,
  AppStrings.instaPay: AppStrings.instaPay,
  AppStrings.coupon: AppStrings.coupon,
  AppStrings.sendRequestCost: AppStrings.sendRequestCost,
  AppStrings.transferNumber: AppStrings.transferNumber,
  AppStrings.clickUploadImage: AppStrings.clickUploadImage,
  AppStrings.enterTheNumber: AppStrings.enterTheNumber,
  AppStrings.transferAccount: AppStrings.transferAccount,
  AppStrings.transferAccountSendFrom: AppStrings.transferAccountSendFrom,
  AppStrings.enterTheCode: AppStrings.enterTheCode,
  AppStrings.allOrders: AppStrings.allOrders,
  AppStrings.acceptOffers: AppStrings.acceptOffers,
  AppStrings.makeOffer: AppStrings.makeOffer,
  AppStrings.time: AppStrings.time,
  AppStrings.visitCode: AppStrings.visitCode,
  AppStrings.offerPrice: AppStrings.offerPrice,
  AppStrings.warranty: AppStrings.warranty,
  AppStrings.deniedOrder: AppStrings.deniedOrder,
  AppStrings.offerDetails: AppStrings.offerDetails,
  AppStrings.previousWork: AppStrings.previousWork,
  AppStrings.askProvider: AppStrings.askProvider,
  AppStrings.order: AppStrings.order,
  AppStrings.expectedDuraction: AppStrings.expectedDuraction,
  AppStrings.area: AppStrings.area,
  AppStrings.location: AppStrings.location,
  AppStrings.addANameForThePickedLocation:
      AppStrings.addANameForThePickedLocation,
  AppStrings.add: AppStrings.add,
  AppStrings.pleaseEnableLocationService:
      AppStrings.pleaseEnableLocationService,
  AppStrings.attachedFiles: AppStrings.attachedFiles,
  AppStrings.myOfferDetails: AppStrings.myOfferDetails,
  AppStrings.doWantToEnd: AppStrings.doWantToEnd,
  AppStrings.finish: AppStrings.finish,
  AppStrings.resendCode: AppStrings.resendCode,
  AppStrings.completed: AppStrings.completed,
  AppStrings.cancelled: AppStrings.cancelled,
  AppStrings.today: AppStrings.today,
  AppStrings.tomorrow: AppStrings.tomorrow,
  AppStrings.nextWeek: AppStrings.nextWeek,
  AppStrings.duringWeek: AppStrings.duringWeek,
  AppStrings.months: AppStrings.months,
  AppStrings.immediately: AppStrings.immediately,
  AppStrings.alreadyBooked: AppStrings.alreadyBooked,
  AppStrings.youGot: AppStrings.youGot,
  AppStrings.request: AppStrings.request,
  AppStrings.witth: AppStrings.witth,
  AppStrings.viewAllOffer: AppStrings.viewAllOffer,
  AppStrings.providedServices: AppStrings.providedServices,
  AppStrings.noDataFound: AppStrings.noDataFound,
  AppStrings.itSeamsLikeYouHaveNotPickedALocation:
      AppStrings.itSeamsLikeYouHaveNotPickedALocation,
  AppStrings.letsDoItAgain: AppStrings.letsDoItAgain,
};
